### PR TITLE
v1.4.6

### PR DESCRIPTION
**Pull request by EstebanDalelR**
v1.4.6

### CODE REVIEW

**Review by baristaGeek — COMMENTED** [review]
Sending email doesn't work. Should we fix it? Or remove it from this release until we nail it well? 

https://user-images.githubusercontent.com/8325094/180262701-95e139c3-11f7-4ba6-80a4-8f338abcdc1b.mov

**Comment by EstebanDalelR** [comment]
> Sending email doesn't work. Should we fix it? Or remove it from this release until we nail it well?

As usual, reproduction steps?
As a developer, why not debug it?
Why is it always just an empty comment?
https://user-images.githubusercontent.com/11527621/180307399-cc878b10-32fc-4c10-a0f3-c798799c0291.mov

**Comment by EstebanDalelR** [comment]
I see it work properly.

https://user-images.githubusercontent.com/11527621/180307590-19ecec31-01bb-484b-a4a9-8264995ec163.mov

**Comment by EstebanDalelR** [comment]
@baristaGeek I see you gave my video a 👎🏻 , why was that?

**Comment by baristaGeek** [comment]
> @baristaGeek I see you gave my video a 👎🏻 , why was that?

Because it's not working for me, as shown on the video I posted.

**Review by baristaGeek — APPROVED** [review]
As discussed on Slack, we'll release like this. We'll fix "email the author" not working for some users later down the road.

**Pull request merged**
