### PR TITLE
Tests/initial flow

### PR DESCRIPTION
**Pull request by EstebanDalelR**
## Description
Added smoke tests

## Type of change
- New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by baristaGeek — COMMENTED** [review]
Something failed. This is the error message. I'm using node 12.x. Did I need to do something else? 

Screen Shot 2022-04-12 at 4 55 22 PM

**Comment by EstebanDalelR** [comment]
There's an await. Might be that. 
Did you `non install`?

**Comment by baristaGeek** [comment]
> There's an await. Might be that. Did you `npm install`? I'll check in my Mac and on azure.

I did npm install. FTR I'm using node 12.

VS Code automatically opens, an alert appears, the whole shebang. But this error appears at the end

**Comment by EstebanDalelR** [comment]
What does the log say?

**Comment by EstebanDalelR** [comment]
After running it myself the log is:
```
Git installation not found.

  Extension Test Suite
    ✔ Sample test
    ✔ Extension is present
    1) Extension is activated
  2 passing (2s)
  1 failing
  1) Extension Test Suite
       Extension is activated:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(vscode.extensions.getExtension("WatermelonTools.watermelon-tools")?.isActive)

      + expected - actual

      -false
      +true
      
  	at Context.<anonymous> (out/test/suite/extension.test.js:23:16)

Error: 1 tests failed.
	at /Users/estebandalel/Documents/GitHub/wm-extension/out/test/suite/index.js:24:27
	at done (/Users/estebandalel/Documents/GitHub/wm-extension/node_modules/mocha/lib/mocha.js:1058:7)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
[main 2022-04-18T17:37:00.644Z] Waiting for extension host with pid 5349 to exit.
[main 2022-04-18T17:37:00.650Z] Extension host with pid 5349 exited with code: 1, signal: null.
Exit code:   1
Failed to run tests
```

**Comment by EstebanDalelR** [comment]
After installing git:
`Loading development extension at /Users/estebandalel/Documents/GitHub/wm-extension

  Extension Test Suite
    ✔ Sample test
    ✔ Extension is present
    1) Extension is activated
  2 passing (2s)
  1 failing
  1) Extension Test Suite
       Extension is activated:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(vscode.extensions.getExtension("WatermelonTools.watermelon-tools")?.isActive)

      + expected - actual

      -false
      +true
      
  	at Context.<anonymous> (out/test/suite/extension.test.js:23:16)

Error: 1 tests failed.
	at /Users/estebandalel/Documents/GitHub/wm-extension/out/test/suite/index.js:24:27
	at done (/Users/estebandalel/Documents/GitHub/wm-extension/node_modules/mocha/lib/mocha.js:1058:7)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
[main 2022-04-18T18:02:50.358Z] Waiting for extension host with pid 5821 to exit.
[main 2022-04-18T18:02:50.359Z] Extension host with pid 5821 exited with code: 1, signal: null.
Exit code:   1
Failed to run tests`

**Review by baristaGeek — APPROVED** [review]
I upgraded node to 14.0.0, VS Code to 1.66.x and Git to the latest version. It worked!

Let's take into account this info.

**Pull request closed without merging**
