### PR TITLE
Fix/paper analytics

### PR DESCRIPTION
**Pull request by EstebanDalelR**
## Description
Reuse Slack button analytics for paper button

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by baristaGeek — COMMENTED** [review]
Is this supposed to be tracked on the slackhelp table? I don't see it there

**Comment by EstebanDalelR** [comment]
> Is this supposed to be tracked on the slackhelp table? I don't see it there

Would you please elaborate?
I pulled the branch, clicked the button and saw the event get saved to the table.
Yes, the naming is wrong but I figured we'd use it for quick experiments and such.

**Comment by baristaGeek** [comment]
> > Is this supposed to be tracked on the slackhelp table? I don't see it there
> 
> Would you please elaborate? I pulled the branch, clicked the button and saw the event get saved to the table. Yes, the naming is wrong but I figured we'd use it for quick experiments and such.

Yeah yeah, naming is fine. 

What I mean is that it didn't track. I'll try again.

**Review by baristaGeek — APPROVED** [review]
Works now

**Comment by EstebanDalelR** [comment]
> Works now

Nothing was changed

**Pull request merged**
