### PR TITLE
Paper button

### PR DESCRIPTION
**Pull request by EstebanDalelR**
## Description
Paper helps users document their code.
It creates a `wm-paper/index.md` file that will be filled in by this.
Also opens the file

## Type of change

- New feature (non-breaking change which adds functionality)
image

### CODE REVIEW

**Review by baristaGeek — CHANGES_REQUESTED** [review]
Am I getting this because I'm missing something?

**Comment by EstebanDalelR** [comment]
> Am I getting this because I'm missing something?
> 
> 

It did not get created, but that's the line just above it

**Comment by EstebanDalelR** [comment]
Please retest @baristaGeek

**Review by baristaGeek — APPROVED** [review]
It works now! Ty

**Pull request merged**
