### PR TITLE
v.1.5.2

### PR DESCRIPTION
**Pull request by EstebanDalelR**
v.1.5.2

### CODE REVIEW

**Review by baristaGeek — CHANGES_REQUESTED** [review]
The new button doesn't work. Should we just revert this to how it was before?
Small GIF (400x198)

**Review by baristaGeek — COMMENTED** [review]
https://user-images.githubusercontent.com/8325094/186794800-aedef16d-db0b-4b4f-9fa9-0e107d8b9ab6.mp4

**Comment by EstebanDalelR** [comment]
> Video.MP4.1038x514.mp4

Literally, this video shows it works...
What's broken?
The code is the same, just wrapped in a table to style it.

**Comment by EstebanDalelR** [comment]
I saw it fail to run, but it also didn't work with the command or the status bar. Something else is up.

**Comment by baristaGeek** [comment]
> I saw it fail to run, but it also didn't work with the command or the status bar. Something else is up.

I will be attentive to see what you wanna do about this. Else, we shouldn't release like this.

**Comment by EstebanDalelR** [comment]
> > I saw it fail to run, but it also didn't work with the command or the status bar. Something else is up.
> 
> I will be attentive to see what you wanna do about this. Else, we shouldn't release like this.

It's weird, I only see one thing that touches a command, "Talk to the CTO," but that's on the `show` command, which works. All the rest is markdown and divs.

**Review by baristaGeek — DISMISSED** [review]
Please merge once you merge #393

**Pull request merged**
