### PR TITLE
Fix error that retrieves PRs from another repo

### PR DESCRIPTION
**Pull request by baristaGeek**
## Description

Fixes a behavior that was very, very confusing for users: Showing PRs from unrelated repos out in the wild. 

Product considerations
- If we add longer SHAs, we would limit the search results we show the user. At least for now, we don't wanna show less results. This is because of Octokit's character length restriction for the `q` parameter.

Technical considerations (behaviors before the implementation of the solution):
- I ran with supabase-js, and sent watermelon as owner and supabase-js. Results were returned normally
- I ran on the Fiskal repo. jabanderstatch as owner and Startup2021...billing...REST_API as reponame. Wrong results (result from the Vue JS repo, for example), where returned
- Because of these 2 behaviors, I concluded that the problem wasn't about the wrong owner parameter value. 

I made a Loom video showing the behavior with Fiskal's repo, and with Platanus' Restmod repo
https://www.loom.com/share/9d2280b09dfa42a9bdc8e0468287c1be

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by EstebanDalelR — CHANGES_REQUESTED** [review]
Please add changelog

**Comment by baristaGeek** [comment]
> Please add changelog

Ok, done

**Review by EstebanDalelR — APPROVED** [review]

**Comment by EstebanDalelR** [comment]
Thank you.
Missing the conflicts (add all lol)

**Comment by EstebanDalelR** [comment]
I renamed this as this did not fix it @baristaGeek

**Pull request merged**
