### PR TITLE
Fix/jira tickets

### PR DESCRIPTION
**Pull request by EstebanDalelR**
## Description
This fixes the Jira issues to allow releasing 1.6.1
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)  
- [ ] New feature (non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [ ] Documentation update  
- [ ] Chore: cleanup/renaming, etc  
- [ ] RFC  
## Acceptance

- [x] I have read [the Contributing guidelines](CONTRIBUTING.md)
- [x] I have read the [Code of Conduct](CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by baristaGeek — COMMENTED** [review]
I'm getting an infinite loading state. Is it working perfectly for you? 

https://www.loom.com/share/4f38dfa2fa3c4b88b21e9b2954e9aad7

**Comment by EstebanDalelR** [comment]
> I'm getting an infinite loading state. Is it working perfectly for you?
> 
> https://www.loom.com/share/4f38dfa2fa3c4b88b21e9b2954e9aad7

getting the same. Please look at Daily Summary while I debug.

**Comment by baristaGeek** [comment]
> > I'm getting an infinite loading state. Is it working perfectly for you?
> > https://www.loom.com/share/4f38dfa2fa3c4b88b21e9b2954e9aad7
> 
> getting the same. Please look at Daily Summary while I debug.

What should I look for in Daily Summary, specifically?

**Comment by EstebanDalelR** [comment]
> I'm getting an infinite loading state. Is it working perfectly for you?
> 
> https://www.loom.com/share/4f38dfa2fa3c4b88b21e9b2954e9aad7

Ah, I see the error. It's a backend thing.

**Comment by EstebanDalelR** [comment]
> > > I'm getting an infinite loading state. Is it working perfectly for you?
> > > https://www.loom.com/share/4f38dfa2fa3c4b88b21e9b2954e9aad7
> > 
> > 
> > getting the same. Please look at Daily Summary while I debug.
> 
> What should I look for in Daily Summary, specifically?

Any errors to be found, any code smells

**Comment by EstebanDalelR** [comment]
> > I'm getting an infinite loading state. Is it working perfectly for you?
> > https://www.loom.com/share/4f38dfa2fa3c4b88b21e9b2954e9aad7
> 
> Ah, I see the error. It's a backend thing.

Fixed both in backend and frontend

**Comment by baristaGeek** [comment]
I'm approving with the error described above. We'll polish this down the road.

**Pull request merged**
