### PR TITLE
Feature/add code author name to slack help button

### PR DESCRIPTION
**Pull request by EstebanDalelR**
## Description

The slack help button will now show a more helpful message
## Type of change

- New feature (non-breaking change which adds functionality)

Screen Shot 2022-04-25 at 6 17 36 PM

### CODE REVIEW

**Review by baristaGeek — CHANGES_REQUESTED** [review]
I would remove the date that appears in some cases
Screen Shot 2022-04-26 at 5 17 22 PM

**Comment by EstebanDalelR** [comment]
I'd like to try, please link the repro repo.
I've updated anyways @baristaGeek

**Comment by baristaGeek** [comment]
> I'd like to try, please link the repro repo. I've updated anyways @baristaGeek

https://github.com/baristaGeek/only-fungs

Play with it on nft.js

**Review by baristaGeek — APPROVED** [review]
Fixed. Looks good.

**Pull request merged**
