### PR TITLE
Feature/loginless value

### PR DESCRIPTION
**Pull request by EstebanDalelR**
## Description
Allows the user to experience a bit of watermelon without GitHub login. Prompts to login.
If the user clicks, the `run` command will be executed to produce immediate results.
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)  
- [x] New feature (non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [ ] Documentation update  
- [ ] Chore: cleanup/renaming, etc  
- [ ] RFC

### CODE REVIEW

**Comment by EstebanDalelR** [comment]
> This works!
> 
> Quick question: When is the user prompted to login in order to get access to the fully-featured Watermelon? I just tried getting code context w/o being logged in. Not sure if I should try something else.

As per `extension.ts`, we use the `GITHUB` login prompt. You get access to the PRs and Daily summary when logged into GitHub.

**Comment by baristaGeek** [comment]
> > This works!
> > Quick question: When is the user prompted to login in order to get access to the fully-featured Watermelon? I just tried getting code context w/o being logged in. Not sure if I should try something else.
> 
> As per `extension.ts`, we use the `GITHUB` login prompt. You get access to the PRs and Daily summary when logged into GitHub.

My question was "when is the user prompted to login?". 

As we just discussed offline, I now understand that "prompts to login" means there is a login button, not a pop-up or something similar. 

Thanks for making this clear. I'll approve.

**Review by baristaGeek — APPROVED** [review]

**Comment by EstebanDalelR** [comment]
Screen Shot 2022-08-31 at 1 05 23 PM


> > > This works!
> > > Quick question: When is the user prompted to login in order to get access to the fully-featured Watermelon? I just tried getting code context w/o being logged in. Not sure if I should try something else.
> > 
> > 
> > As per `extension.ts`, we use the `GITHUB` login prompt. You get access to the PRs and Daily summary when logged into GitHub.
> 
> My question was "when is the user prompted to login?".
> 
> As we just discussed offline, I now understand that "prompts to login" means there is a login button, not a pop-up or something similar.
> 
> Thanks for making this clear. I'll approve.

The user gets a big "Get Code Context" button under Pull Requests. This starts the login flow.
I just noticed that Daily Summary should also have it.

**Comment by EstebanDalelR** [comment]
Screen Shot 2022-08-31 at 1 13 22 PM
I have added a Daily Summary prompt and changed the button text

**Pull request merged**
